# Q1
```sql
SELECT TITLE,DESCRIPTION FROM FILM;
```

# Q2
```sql
SELECT * FROM FILM WHERE LENGTH > 60 AND LENGTH <75;
```

# Q3
```sql
SELECT * FROM FILM WHERE RENTAL_RATE = 0.99 AND (REPLACEMENT_COST=12.99 OR REPLACEMENT_COST=28.99);
```

# Q4
```sql
SELECT LAST_NAME FROM CUSTOMER WHERE FIRST_NAME = 'Mary';
```

# Q5
```sql
SELECT * FROM FILM LENGTH <=50 AND RENTAL_RATE NOT IN (2.99,4.99);
```
